/* Generated by Together */

package ch.jfactory.collection.cursor;

public interface CursorChangeListener
{
    void cursorChange(CursorChangeEvent event);

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Observer
     * @clientRole Observer
     * @supplierRole <{com.ethz.geobot.herbar.util.cursor.NotifiableCursor}>
     */
    /*# private NotifiableCursor _subject; */
}
