/*
 * Copyright (c) 2004-2011, Daniel Frey, www.xmatrix.ch
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed  under this License is distributed on an "AS IS" BASIS,
 * WITHOUT  WARRANTIES OR CONDITIONS OF  ANY  KIND, either  express or
 * implied.  See  the  License  for  the  specific  language governing
 * permissions and limitations under the License.
 */

/* Generated by Together */
package ch.jfactory.collection.cursor;

public interface CursorChangeListener
{
    void cursorChange( CursorChangeEvent event );

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Observer
     * @clientRole Observer
     * @supplierRole <{com.ethz.geobot.herbar.util.cursor.NotifiableCursor}>
     */
    /*# private NotifiableCursor _subject; */
}
