/*
 * Copyright (c) 2004-2011, Daniel Frey, www.xmatrix.ch
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed  under this License is distributed on an "AS IS" BASIS,
 * WITHOUT  WARRANTIES OR CONDITIONS OF  ANY  KIND, either  express or
 * implied.  See  the  License  for  the  specific  language governing
 * permissions and limitations under the License.
 */

/* Generated by Together */
package ch.jfactory.update;

import java.util.EventListener;

public interface UpdateChangeListener extends EventListener
{
    /**
     * this method is invoke if the UpdateProcessor begins update.
     *
     * @param event information aboud the update state
     */
    void beginUpdate( UpdateChangeEvent event );

    /**
     * this method is invoke if the UpdateProcessor begins update.
     *
     * @param event information aboud the update state
     */
    void progressUpdate( UpdateChangeEvent event );

    /**
     * this method is invoke if the UpdateProcessor finish update.
     *
     * @param event information aboud the update state
     */
    void finishUpdate( UpdateChangeEvent event );
    /** @link dependency */
    /*# UpdateChangeEvent lnkUpdateChangeEvent; */
}
