package ch.xmatrix.ups.pmb.test;

import ch.jfactory.file.FileUtils;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import org.apache.commons.io.IOUtils;

/**
 * // TODO: Comment
 *
 * @author Daniel Frey 07.07.2008 22:07:03
 */
public class TestTaxa
{
    public static String getTestPictures() throws IOException
    {
        final String[] files = {
                "/test/test.xml",
                "/test/Abies alba/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Abies alba/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Abies alba/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Abies alba/Blatt.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Abies alba/Blatt.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Abies alba/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Abies alba/Blüte (0 100 0 100).jpg",
                "/test/Abies alba/Blüte.Detail (0 100 0 100).jpg",
                "/test/Abies alba/Blüte.Detail.Detail (0 100 0 100).jpg",
                "/test/Abies alba/Habitus (0 100 0 100).jpg",
                "/test/Abies alba/Herbar (0 100 0 100).jpg",
                "/test/Abies alba/Rinde (0 100 0 100).jpg",
                "/test/Abies alba/Rinde.Detail (0 100 0 100).jpg",
                "/test/Abies alba/Samen+.Oberseite (0 100 0 100).jpg",
                "/test/Abies alba/Samen.Unterseite (0 100 0 100).jpg",
                "/test/Abies alba/Standort (0 100 0 100).jpg",
                "/test/Abies alba/Standort.Detail (0 100 0 100).jpg",
                "/test/Abies alba/Zapfen+.jung (0 100 0 100).jpg",
                "/test/Abies alba/Zapfen.alt (0 100 0 100).jpg",
                "/test/Abies alba/Zapfen.alt.Detail (0 100 0 100).jpg",
                "/test/Abies alba/Zapfen.jung.Detail (0 100 0 100).jpg",
                "/test/Abies alba/Zapfen.jung.Detail.Detail (0 100 0 100).jpg",
                "/test/Abies alba/Zweig (0 100 0 100).jpg",
                "/test/Abies alba/Zweig.Detail (0 100 0 100).jpg",
                "/test/Abies alba/Zweig.Detail.Detail (0 100 0 100).jpg",
                "/test/Abies alba/Zweig.Oberseite (0 100 0 100).jpg",
                "/test/Abies alba/Zweig.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Abies alba/Zweig.Unterseite (0 100 0 100).jpg",
                "/test/Abies alba/Zweig.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Acer platanoides/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Acer platanoides/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Acer platanoides/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Acer platanoides/Blatt.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Acer platanoides/Blatt.Rand+.Oberseite (0 100 0 100).jpg",
                "/test/Acer platanoides/Blatt.Rand.Unterseite (0 100 0 100).jpg",
                "/test/Acer platanoides/Blatt.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Acer platanoides/Blatt.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Acer platanoides/Blatt.Stiel (0 100 0 100).jpg",
                "/test/Acer platanoides/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Acer platanoides/Blatt.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Acer platanoides/Blüte (0 100 0 100).jpg",
                "/test/Acer platanoides/Blüte.Detail (0 100 0 100).jpg",
                "/test/Acer platanoides/Blüte.Detail.Detail (0 100 0 100).jpg",
                "/test/Acer platanoides/Frucht (0 100 0 100).jpg",
                "/test/Acer platanoides/Frucht.Basis (0 100 0 100).jpg",
                "/test/Acer platanoides/Frucht.Spitze (0 100 0 100).jpg",
                "/test/Acer platanoides/Habitus (0 100 0 100).jpg",
                "/test/Acer platanoides/Herbar (0 100 0 100).jpg",
                "/test/Acer platanoides/Rinde (0 100 0 100).jpg",
                "/test/Acer platanoides/Rinde.Detail (0 100 0 100).jpg",
                "/test/Acer platanoides/Standort (0 100 0 100).jpg",
                "/test/Acer platanoides/Standort.Detail (0 100 0 100).jpg",
                "/test/Acer platanoides/Zweig (0 100 0 100).jpg",
                "/test/Acer platanoides/Zweig.Detail (0 100 0 100).jpg",
                "/test/Asplenium viride/Blatt+.jung+.Oberseite (0 100 0 100).jpg",
                "/test/Asplenium viride/Blatt.alt+.Oberseite (0 100 0 100).jpg",
                "/test/Asplenium viride/Blatt.alt.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Asplenium viride/Blatt.alt.Unterseite (0 100 0 100).jpg",
                "/test/Asplenium viride/Blatt.alt.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Asplenium viride/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Asplenium viride/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Asplenium viride/Blatt.jung.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Asplenium viride/Blatt.jung.Unterseite (0 100 0 100).jpg",
                "/test/Asplenium viride/Blatt.jung.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Asplenium viride/Habitus (0 100 0 100).jpg",
                "/test/Asplenium viride/Herbar (0 100 0 100).jpg",
                "/test/Asplenium viride/Standort (0 100 0 100).jpg",
                "/test/Asplenium viride/Standort.Detail (0 100 0 100).jpg",
                "/test/Athyrium filix-femina/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Athyrium filix-femina/Blatt.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Athyrium filix-femina/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Athyrium filix-femina/Blatt.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Athyrium filix-femina/Habitus (0 100 0 100).jpg",
                "/test/Athyrium filix-femina/Herbar (0 100 0 100).jpg",
                "/test/Athyrium filix-femina/Standort (0 100 0 100).jpg",
                "/test/Athyrium filix-femina/Standort.Detail (0 100 0 100).jpg",
                "/test/Bromus tectorum/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Bromus tectorum/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Bromus tectorum/Blatt.Basis.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Bromus tectorum/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Bromus tectorum/Blatt.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Bromus tectorum/Blatt.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Bromus tectorum/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Bromus tectorum/Blütenstand (0 100 0 100).jpg",
                "/test/Bromus tectorum/Blütenstand.Detail (0 100 0 100).jpg",
                "/test/Bromus tectorum/Blütenstand.Detail.Detail (0 100 0 100).jpg",
                "/test/Bromus tectorum/Habitus (0 100 0 100).jpg",
                "/test/Bromus tectorum/Herbar (0 100 0 100).jpg",
                "/test/Bromus tectorum/Standort (0 100 0 100).jpg",
                "/test/Bromus tectorum/Standort.Detail (0 100 0 100).jpg",
                "/test/Bromus tectorum/Stengel (0 100 0 100).jpg",
                "/test/Bromus tectorum/Stengel.Detail (0 100 0 100).jpg",
                "/test/Bromus tectorum/Wurzel (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Blatt.Detail (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Blatt.Mitte+.Oberseite (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Blatt.Mitte.Unterseite (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Blatt.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Blatt.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Blüte.Oberseite (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Blüte.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Blüte.Unterseite (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Blüte.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Frucht.Detail (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Frucht.geöffnet (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Frucht.geöffnet.Detail (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Habitus (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Herbar (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Standort (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Standort.Detail (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Stengel (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Stengel.Detail (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Stengel.Detail.Detail (0 100 0 100).jpg",
                "/test/Capsella bursa-pastoris/Wurzel (0 100 0 100).jpg",
                "/test/Erigeron annuus/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Erigeron annuus/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Erigeron annuus/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Erigeron annuus/Blatt.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Erigeron annuus/Blatt.Rand+.Oberseite (0 100 0 100).jpg",
                "/test/Erigeron annuus/Blatt.Rand.Unterseite (0 100 0 100).jpg",
                "/test/Erigeron annuus/Blatt.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Erigeron annuus/Blatt.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Erigeron annuus/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Erigeron annuus/Blatt.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Erigeron annuus/Blüte (0 100 0 100).jpg",
                "/test/Erigeron annuus/Blüte.Oberseite (0 100 0 100).jpg",
                "/test/Erigeron annuus/Blüte.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Erigeron annuus/Blüte.Unterseite (0 100 0 100).jpg",
                "/test/Erigeron annuus/Blüte.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Erigeron annuus/Frucht (0 100 0 100).jpg",
                "/test/Erigeron annuus/Frucht.Detail (0 100 0 100).jpg",
                "/test/Erigeron annuus/Habitus (0 100 0 100).jpg",
                "/test/Erigeron annuus/Herbar (0 100 0 100).jpg",
                "/test/Erigeron annuus/Jungpflanze (0 100 0 100).jpg",
                "/test/Erigeron annuus/Standort (0 100 0 100).jpg",
                "/test/Erigeron annuus/Standort.Detail (0 100 0 100).jpg",
                "/test/Erigeron annuus/Standort.Detail.Detail (0 100 0 100).jpg",
                "/test/Erigeron annuus/Stengel (0 100 0 100).jpg",
                "/test/Erigeron annuus/Stengel.Detail (0 100 0 100).jpg",
                "/test/Erigeron annuus/Wurzel (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Blatt.Mitte+.Oberseite (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Blatt.Mitte.Unterseite (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Blatt.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Blatt.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Blütenstand (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Blütenstand.Detail (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Blütenstand.Detail.Detail (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Habitus (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Herbar (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Standort (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Standort.Detail (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Stengel (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Stengel.Detail (0 100 0 100).jpg",
                "/test/Eriophorum angustifolium/Wurzel (0 100 0 100).jpg",
                "/test/Lemna minor/Blatt (0 100 0 100).jpg",
                "/test/Lemna minor/Habitus (0 100 0 100).jpg",
                "/test/Lemna minor/Herbar (0 100 0 100).jpg",
                "/test/Lemna minor/Standort (0 100 0 100).jpg",
                "/test/Lemna minor/Standort.Detail (0 100 0 100).jpg",
                "/test/Lemna minor/Standort.Detail.Detail (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Blatt.Rand+.Oberseite (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Blatt.Rand.Unterseite (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Blatt.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Blatt.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Blüte (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Blüte.Detail (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Blüte.Detail.Detail (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Frucht (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Frucht.Detail (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Habitus (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Herbar+.Frühling (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Herbar.Herbst (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Herbar (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Standort (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Standort.Detail (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Zweig (0 100 0 100).jpg",
                "/test/Ligustrum vulgare/Zweig.Detail (0 100 0 100).jpg",
                "/test/Neottia nidus-avis/Blüte (0 100 0 100).jpg",
                "/test/Neottia nidus-avis/Blüte.Oberseite (0 100 0 100).jpg",
                "/test/Neottia nidus-avis/Blüte.Seite (0 100 0 100).jpg",
                "/test/Neottia nidus-avis/Frucht (0 100 0 100).jpg",
                "/test/Neottia nidus-avis/Frucht.Detail (0 100 0 100).jpg",
                "/test/Neottia nidus-avis/Habitus (0 100 0 100).jpg",
                "/test/Neottia nidus-avis/Herbar (0 100 0 100).jpg",
                "/test/Neottia nidus-avis/Standort (0 100 0 100).jpg",
                "/test/Neottia nidus-avis/Standort.Detail (0 100 0 100).jpg",
                "/test/Neottia nidus-avis/Standort.Detail.Detail (0 100 0 100).jpg",
                "/test/Neottia nidus-avis/Stengel (0 100 0 100).jpg",
                "/test/Neottia nidus-avis/Stengel.Detail (0 100 0 100).jpg",
                "/test/Neottia nidus-avis/Wurzel (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt+.grundständig+.Oberseite (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt.grundständig.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt.grundständig.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt.grundständig.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt.grundständig.Rand+.Oberseite (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt.grundständig.Rand.Unterseite (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt.grundständig.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt.grundständig.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt.grundständig.Stiel+.Oberseite (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt.grundständig.Stiel.Unterseite (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt.grundständig.Unterseite (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt.grundständig.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt.stengelständig+.Oberseite (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt.stengelständig.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt.stengelständig.Unterseite (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blatt.stengelständig.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blüte (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blüte.Detail (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blüte.Oberseite (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blüte.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blüte.Unterseite (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Blüte.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Frucht (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Frucht.Detail (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Habitus (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Herbar (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Standort (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Standort.Detail (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Stengel (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Stengel.Detail (0 100 0 100).jpg",
                "/test/Phyteuma orbiculare/Wurzel (0 100 0 100).jpg",
                "/test/Poa pratensis/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Poa pratensis/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Poa pratensis/Blatt.Basis.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Poa pratensis/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Poa pratensis/Blatt.Mitte+.Oberseite (0 100 0 100).jpg",
                "/test/Poa pratensis/Blatt.Mitte.Unterseite (0 100 0 100).jpg",
                "/test/Poa pratensis/Blatt.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Poa pratensis/Blatt.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Poa pratensis/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Poa pratensis/Blütenstand (0 100 0 100).jpg",
                "/test/Poa pratensis/Blütenstand.Detail (0 100 0 100).jpg",
                "/test/Poa pratensis/Blütenstand.Detail.Detail (0 100 0 100).jpg",
                "/test/Poa pratensis/Habitus (0 100 0 100).jpg",
                "/test/Poa pratensis/Herbar (0 100 0 100).jpg",
                "/test/Poa pratensis/Standort (0 100 0 100).jpg",
                "/test/Poa pratensis/Standort.Detail (0 100 0 100).jpg",
                "/test/Poa pratensis/Stengel (0 100 0 100).jpg",
                "/test/Poa pratensis/Stengel.Detail (0 100 0 100).jpg",
                "/test/Poa pratensis/Stengel.Detail.Detail (0 100 0 100).jpg",
                "/test/Poa pratensis/Wurzel (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blatt.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blatt.Rand+.Oberseite (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blatt.Rand.Unterseite (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blatt.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blatt.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blatt.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blüte+.Blütenstand (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blüte.Oberseite (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blüte.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blüte.Oberseite.Detail.Detail (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blüte.Unterseite (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Blüte.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Frucht (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Herbar (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Standort (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Standort.Detail (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Stengel (0 100 0 100).jpg",
                "/test/Polygonatum odoratum/Wurzel (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blatt.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blatt.Rand+.Oberseite (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blatt.Rand.Unterseite (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blatt.Rand.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blatt.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blatt.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blatt.Stiel+.Oberseite (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blatt.Stiel.Unterseite (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blatt.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blatt.Unterseite.Detail.Detail (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blüte+.Oberseite (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blüte.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blüte.Unterseite (0 100 0 100).jpg",
                "/test/Potentilla reptans/Blüte.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Potentilla reptans/Frucht (0 100 0 100).jpg",
                "/test/Potentilla reptans/Frucht.geöffnet (0 100 0 100).jpg",
                "/test/Potentilla reptans/Habitus (0 100 0 100).jpg",
                "/test/Potentilla reptans/Herbar (0 100 0 100).jpg",
                "/test/Potentilla reptans/Standort (0 100 0 100).jpg",
                "/test/Potentilla reptans/Standort.Detail (0 100 0 100).jpg",
                "/test/Potentilla reptans/Standort.Detail.Detail (0 100 0 100).jpg",
                "/test/Potentilla reptans/Stengel (0 100 0 100).jpg",
                "/test/Potentilla reptans/Stengel.Detail (0 100 0 100).jpg",
                "/test/Potentilla reptans/Stengel.Detail.Detail (0 100 0 100).jpg",
                "/test/Potentilla reptans/Wurzel (0 100 0 100).jpg",
                "/test/Quercus petraea/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Quercus petraea/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Quercus petraea/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Quercus petraea/Blatt.Basis.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Quercus petraea/Blatt.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Quercus petraea/Blatt.Rand+.Oberseite (0 100 0 100).jpg",
                "/test/Quercus petraea/Blatt.Rand.Unterseite (0 100 0 100).jpg",
                "/test/Quercus petraea/Blatt.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Quercus petraea/Blatt.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Quercus petraea/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Quercus petraea/Blatt.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Quercus petraea/Blüte.sitzend+.jung (0 100 0 100).jpg",
                "/test/Quercus petraea/Blüte.sitzend.alt (0 100 0 100).jpg",
                "/test/Quercus petraea/Frucht (0 100 0 100).jpg",
                "/test/Quercus petraea/Frucht.Detail (0 100 0 100).jpg",
                "/test/Quercus petraea/Habitus (0 100 0 100).jpg",
                "/test/Quercus petraea/Herbar (0 100 0 100).jpg",
                "/test/Quercus petraea/Rinde (0 100 0 100).jpg",
                "/test/Quercus petraea/Standort (0 100 0 100).jpg",
                "/test/Quercus petraea/Zweig (0 100 0 100).jpg",
                "/test/Quercus petraea/Zweig.Detail (0 100 0 100).jpg",
                "/test/Ranunculus repens/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Ranunculus repens/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Ranunculus repens/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Ranunculus repens/Blatt.Rand+.Oberseite (0 100 0 100).jpg",
                "/test/Ranunculus repens/Blatt.Rand.Unterseite (0 100 0 100).jpg",
                "/test/Ranunculus repens/Blatt.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Ranunculus repens/Blatt.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Ranunculus repens/Blatt.Stiel+.Oberseite (0 100 0 100).jpg",
                "/test/Ranunculus repens/Blatt.Stiel.Unterseite (0 100 0 100).jpg",
                "/test/Ranunculus repens/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Ranunculus repens/Blüte+.Oberseite (0 100 0 100).jpg",
                "/test/Ranunculus repens/Blüte.Blütenblatt.Detail (0 100 0 100).jpg",
                "/test/Ranunculus repens/Blüte.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Ranunculus repens/Blüte.Unterseite (0 100 0 100).jpg",
                "/test/Ranunculus repens/Blüte.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Ranunculus repens/Frucht (0 100 0 100).jpg",
                "/test/Ranunculus repens/Frucht.Detail (0 100 0 100).jpg",
                "/test/Ranunculus repens/Habitus (0 100 0 100).jpg",
                "/test/Ranunculus repens/Herbar (0 100 0 100).jpg",
                "/test/Ranunculus repens/Standort (0 100 0 100).jpg",
                "/test/Ranunculus repens/Standort.Detail (0 100 0 100).jpg",
                "/test/Ranunculus repens/Standort.Detail.Detail (0 100 0 100).jpg",
                "/test/Ranunculus repens/Stengel (0 100 0 100).jpg",
                "/test/Ranunculus repens/Stengel.Detail (0 100 0 100).jpg",
                "/test/Ranunculus repens/Wurzel (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Blatt.Mitte+.Oberseite (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Blatt.Mitte.Unterseite (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Blatt.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Blatt.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Blüte (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Blüte.Detail (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Blüte.Detail.Detail (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Frucht (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Frucht.Detail (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Habitus (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Herbar (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Standort (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Standort.Detail (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Zweig (0 100 0 100).jpg",
                "/test/Robinia pseudoacacia/Zweig.Detail (0 100 0 100).jpg",
                "/test/Silene dioica M/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Silene dioica M/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Silene dioica M/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Silene dioica M/Blatt.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Silene dioica M/Blatt.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Silene dioica M/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Silene dioica M/Blatt.Unterseite.Detail (0 100 0 100).jpg",
                "/test/Silene dioica M/Blüte (0 100 0 100).jpg",
                "/test/Silene dioica M/Blüte.Oberseite (0 100 0 100).jpg",
                "/test/Silene dioica M/Blüte.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Silene dioica M/Habitus (0 100 0 100).jpg",
                "/test/Silene dioica M/Herbar (0 100 0 100).jpg",
                "/test/Silene dioica M/Standort (0 100 0 100).jpg",
                "/test/Silene dioica M/Standort.Detail (0 100 0 100).jpg",
                "/test/Silene dioica M/Stengel (0 100 0 100).jpg",
                "/test/Silene dioica M/Stengel.Detail (0 100 0 100).jpg",
                "/test/Silene dioica M/Wurzel (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Blatt+.Oberseite (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Blatt.Basis+.Oberseite (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Blatt.Basis.Unterseite (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Blatt.Mitte+.Oberseite (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Blatt.Mitte.Unterseite (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Blatt.Spitze+.Oberseite (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Blatt.Spitze.Unterseite (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Blatt.Unterseite (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Blüte (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Blüte.Oberseite (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Blüte.Oberseite.Detail (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Blüte.Unterseite (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Habitus (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Herbar (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Standort (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Standort.Detail (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Stengel (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Stengel.Detail (0 100 0 100).jpg",
                "/test/Vincetoxicum hirundinaria/Wurzel (0 100 0 100).jpg"
        };
        final File directory = FileUtils.createTemporaryDirectory( "pmbx", "" );
        directory.deleteOnExit();
        for ( final String file : files )
        {
            final InputStream in = TestTaxa.class.getResourceAsStream( file );
            if ( in == null )
            {
                throw new IllegalStateException( "resource not found: " + file );
            }
            final File absoluteFile = new File( directory, file );
            absoluteFile.getParentFile().mkdirs();
            final FileOutputStream out = new FileOutputStream( absoluteFile );
            IOUtils.copy( in, out );
            IOUtils.closeQuietly( out );
            IOUtils.closeQuietly( in );
        }
        return directory.getAbsolutePath();
    }
}
